version: '3.8'

services:
  # Servicio de Nginx (Proxy Inverso + Frontend)
  proxy:
    image: bus-ticket-app-proxy
    deploy:
      replicas: 3  
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.5'  
          memory: 256M  
    ports:
      - "80:80"  
    networks:
      - red-overlay
    depends_on:
      - user-auth
      - bus-reservation
      - payment-gateway
      - route-scheduler

  user-auth:
    image: bus-ticket-app-user-auth
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - red-overlay

  bus-reservation:
    image: bus-ticket-app-bus-reservation
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - red-overlay

  payment-gateway:
    image: bus-ticket-app-payment-gateway
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - red-overlay

  route-scheduler:
    image: bus-ticket-app-route-scheduler
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - red-overlay

networks:
  red-overlay:
    driver: overlay  
